### ISSUE TITLE
Not possible to avoid `native-tls` feature of `reqwest`

### ISSUE THREAD

**Issue by silwol** [niuhuan/reqwest_dav#2]
I would like to add `reqwest_dav` as a dependency to my project. I want to use the `rustls-tls` feature of `reqwest`, and not have `native-tls` (which pulls in `openssl` as a dependency) in the build tree at all.

Adding `default-features = false` to the `reqwest` dependency could help here, it would allow users of `reqwest_dav` to add their own dependency on `reqwest` and set the features as preferred.

As a bonus, passing through the `rustls-tls` and `native-tls` features would facilitate selection of these, possibly mirroring the behavior of `reqwest` so that users who don't care at all have no extra work to do.

**Comment by niuhuan** [comment]
I'm sorry that these codes only complete basic functions.

These things may be useful to you

- streaming or better digest ? : https://github.com/niuhuan/reqwest_dav/compare/master...APG-lab:reqwest_dav:streaming
- getetag maybe Option ?  #1
